export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_PAYMENT_DETAIL = 'USER_PAYMENT_DETAIL';
export const USER_PAYMENT_FAIL = 'USER_PAYMENT_FAIL';
export const USER_PAYMENT_RESET = 'USER_PAYMENT_RESET';

export const PAYMENT_METHODS = 'PAYMENT_METHODS';
export const PAYMENT_METHODS_FAIL = 'PAYMENT_METHODS_FAIL';
export const PAYMENT_METHODS_RESET = 'PAYMENT_METHODS_RESET';

export const DETAIL_VOUCHER = 'DETAIL_VOUCHER';
export const DETAIL_VOUCHER_FAIL = 'DETAIL_VOUCHER_FAIL';
export const DETAIL_VOUCHER_RESET = 'DETAIL_VOUCHER_RESET'; 